name: Sync with Hugging Face

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Install huggingface-hub
        run: pip install huggingface-hub

      - name: Configure git
        run: |
          git config --global user.email "simon@roske.com"
          git config --global user.name "ubuti"

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Clone the Hugging Face repository using the 'space' remote
          git clone https://huggingface.co/ubuti/MRI_tumor_classification hf-repo
          
          # Copy the contents of the GitHub repository to the Hugging Face repository
          rsync -av --exclude='.git' . hf-repo/
          
          # Change to the Hugging Face directory
          cd hf-repo
          
          # Add the 'space' remote to your Hugging Face repo directory
          git remote add space https://ubuti:${HF_TOKEN}@huggingface.co/ubuti/MRI_tumor_classification

          # Check if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync with GitHub"
            git push space main
          else
            echo "No changes to sync."
          fi
