name: Sync with Hugging Face

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Install huggingface-hub
        run: pip install huggingface-hub

      - name: Configure git
        run: |
          git config --global user.email "simon@roske.com"
          git config --global user.name "ubuti"

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add Hugging Face as a remote
          git remote add hf https://ubuti:${HF_TOKEN}@huggingface.co/ubuti/MRI_tumor_classification
          
          # Push changes to the Hugging Face repository
          git push hf main  # Change 'main' if you're using a different branch
